name: 'Sobelow Test'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with: 
        otp-version: '22.2'
        elixir-version: '1.9.4'
    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get --only test
    - run: mix compile
    - name: Run Sobelow
      run: mix sobelow --format sarif > results.sarif
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
