name: "Sobelow Analysis"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
    - uses: GriffinMB/phx_demo
